<?php

return [
    'plans' => [
        'free' => [
            'name' => 'Free',
            'tier' => 'free',
            'features' => [
                'Full basic session setup',
                '3 saved sessions',
                'Basic analytics',
                'Focus mode',
            ],
        ],
        'premium_monthly' => [
            'name' => 'Premium',
            'tier' => 'premium',
            'interval' => 'month',
            'price_id' => env('STRIPE_PRICE_PREMIUM_MONTHLY', 'price_1Tfgi9KHwZ9fhmRpJo4NOuH6'),
            'trial_days' => 7,
            'features' => [
                'Full basic session setup',
                '5 saved sessions',
                'Focus mode',
                'Blurring method',
                'Chaining method',
                'Anchor mode',
                'Basic analytics',
                'Manual self-assessment recording',
                'Structured Custom Hifz Plan',
                'Spaced Session Retention',
                'Adaptive Revision Scheduling',
                'Progress Tracking',
            ],
        ],
        'premium_yearly' => [
            'name' => 'Premium',
            'tier' => 'premium',
            'interval' => 'year',
            'price_id' => env('STRIPE_PRICE_PREMIUM_YEARLY', 'price_1TfgmNKHwZ9fhmRpoCjP7TFg'),
            'trial_days' => 7,
            'features' => [
                'Full basic session setup',
                '5 saved sessions',
                'Focus mode',
                'Blurring method',
                'Chaining method',
                'Anchor mode',
                'Basic analytics',
                'Manual self-assessment recording',
                'Structured Custom Hifz Plan',
                'Spaced Session Retention',
                'Adaptive Revision Scheduling',
                'Progress Tracking',
            ],
        ],
        'pro_monthly' => [
            'name' => 'Pro',
            'tier' => 'pro',
            'interval' => 'month',
            'price_id' => env('STRIPE_PRICE_PRO_MONTHLY', 'price_1TfgjCKHwZ9fhmRpBH7jVtk9'),
            'trial_days' => 7,
            'features' => [
                'Full basic session setup',
                'Unlimited saved sessions',
                'All memorisation techniques included',
                'AI recitation',
                'AI memorisation checker',
                'Manual self-assessment recording + self recording',
                'Advanced analysis',
                'Download for offline listening',
                'Structured Custom Hifz Plan',
                'Spaced Session Retention',
                'Voice Hifz Plan Builder',
                'Adaptive Revision Scheduling',
                'Progress Tracking',
            ],
        ],
        'pro_yearly' => [
            'name' => 'Pro',
            'tier' => 'pro',
            'interval' => 'year',
            'price_id' => env('STRIPE_PRICE_PRO_YEARLY', 'price_1TfglnKHwZ9fhmRpAoaX2bjr'),
            'trial_days' => 7,
            'features' => [
                'Full basic session setup',
                'Unlimited saved sessions',
                'All memorisation techniques included',
                'AI recitation',
                'AI memorisation checker',
                'Manual self-assessment recording + self recording',
                'Advanced analysis',
                'Download for offline listening',
                'Structured Custom Hifz Plan',
                'Spaced Session Retention',
                'Voice Hifz Plan Builder',
                'Adaptive Revision Scheduling',
                'Progress Tracking',
            ],
        ],
    ],
];
