<?php

return [
    'currency' => env('BILLING_CURRENCY', 'GBP'),
    'currency_symbol' => env('BILLING_CURRENCY_SYMBOL', '£'),
    'plans' => [
        'free' => [
            'name' => 'Free',
            'tier' => 'free',
            'features' => [
                'Basic session setup',
                'Quranic fonts',
                '5 free smart recitation checks',
                '3 saved sessions',
                'Basic insights',
            ],
        ],
        'premium_monthly' => [
            'name' => 'Premium',
            'tier' => 'premium',
            'interval' => 'month',
            'price_id' => env('STRIPE_PRICE_PREMIUM_MONTHLY'),
            'trial_days' => 7,
            'features' => [
                'Full basic session setup',
                '5 saved sessions',
                'Focus mode',
                'Blurring method',
                'Chaining method',
                'Anchor mode',
                'Basic analytics',
                'Manual self-assessment recording',
                'Structured Custom Hifz Plan',
                'Spaced Session Retention',
                'Adaptive Revision Scheduling',
                'Progress Tracking',
            ],
        ],
        'premium_yearly' => [
            'name' => 'Premium',
            'tier' => 'premium',
            'interval' => 'year',
            'price_id' => env('STRIPE_PRICE_PREMIUM_YEARLY'),
            'trial_days' => 7,
            'features' => [
                'Full basic session setup',
                '5 saved sessions',
                'Focus mode',
                'Blurring method',
                'Chaining method',
                'Anchor mode',
                'Basic analytics',
                'Manual self-assessment recording',
                'Structured Custom Hifz Plan',
                'Spaced Session Retention',
                'Adaptive Revision Scheduling',
                'Progress Tracking',
            ],
        ],
        'pro_monthly' => [
            'name' => 'Pro',
            'tier' => 'pro',
            'interval' => 'month',
            'price_id' => env('STRIPE_PRICE_PRO_MONTHLY'),
            'trial_days' => 7,
            'display_amount' => '5.99',
            'features' => [
                'Everything in the Free plan',
                '20 smart recitation checks',
                'Download audio to listen offline',
                'Adaptive lesson plans',
                'Instant feedback on your recitation',
                'Advanced progress insights',
                'Review past mistakes and weak ayahs',
                'Advanced practice tools',
                'Unlimited saved sessions',
            ],
        ],
        'pro_yearly' => [
            'name' => 'Pro',
            'tier' => 'pro',
            'interval' => 'year',
            'price_id' => env('STRIPE_PRICE_PRO_YEARLY'),
            'trial_days' => 7,
            'display_amount' => '53.91',
            'display_monthly_equivalent' => '4.49',
            'annual_discount_percent' => 25,
            'features' => [
                'Everything in the Free plan',
                '20 smart recitation checks',
                'Download audio to listen offline',
                'Adaptive lesson plans',
                'Instant feedback on your recitation',
                'Advanced progress insights',
                'Review past mistakes and weak ayahs',
                'Advanced practice tools',
                'Unlimited saved sessions',
            ],
        ],
    ],
];
