<?php

return [
    'currency' => env('BILLING_CURRENCY', 'GBP'),
    'currency_symbol' => env('BILLING_CURRENCY_SYMBOL', '£'),
    'plans' => [
        'free' => [
            'name' => 'Free',
            'tier' => 'free',
            'features' => [
                'Session setup, reciter, range, and repetitions',
                'Audio speed, auto-advance, and delays',
                'One ayah at a time',
                'Gradually hide the text',
                'Listen and repeat',
                '3 saved sessions',
                'Basic analytics',
            ],
        ],
        'premium_monthly' => [
            'name' => 'Premium',
            'tier' => 'premium',
            'interval' => 'month',
            'price_id' => env('STRIPE_PRICE_PREMIUM_MONTHLY'),
            'trial_days' => 7,
            'features' => [
                'Full basic session setup',
                '5 saved sessions',
                'Focus mode',
                'Blurring method',
                'Chaining method',
                'Anchor mode',
                'Basic analytics',
                'Manual self-assessment recording',
                'Structured Custom Hifz Plan',
                'Spaced Session Retention',
                'Adaptive Revision Scheduling',
                'Progress Tracking',
            ],
        ],
        'premium_yearly' => [
            'name' => 'Premium',
            'tier' => 'premium',
            'interval' => 'year',
            'price_id' => env('STRIPE_PRICE_PREMIUM_YEARLY'),
            'trial_days' => 7,
            'features' => [
                'Full basic session setup',
                '5 saved sessions',
                'Focus mode',
                'Blurring method',
                'Chaining method',
                'Anchor mode',
                'Basic analytics',
                'Manual self-assessment recording',
                'Structured Custom Hifz Plan',
                'Spaced Session Retention',
                'Adaptive Revision Scheduling',
                'Progress Tracking',
            ],
        ],
        'pro_monthly' => [
            'name' => 'Pro',
            'tier' => 'pro',
            'interval' => 'month',
            'price_id' => env('STRIPE_PRICE_PRO_MONTHLY'),
            'trial_days' => 7,
            'display_amount' => '5.99',
            'features' => [
                'Full basic session setup',
                'Unlimited saved sessions',
                'Join ayahs together and memory-word highlights',
                'AI recitation',
                'AI memorisation checker',
                'Manual self-assessment recording + self recording',
                'Advanced analysis',
                'Download for offline listening',
                'Structured Custom Hifz Plan',
                'Spaced Session Retention',
                'Adaptive Revision Scheduling',
                'Progress Tracking',
            ],
        ],
        'pro_yearly' => [
            'name' => 'Pro',
            'tier' => 'pro',
            'interval' => 'year',
            'price_id' => env('STRIPE_PRICE_PRO_YEARLY'),
            'trial_days' => 7,
            'display_amount' => '53.91',
            'display_monthly_equivalent' => '4.49',
            'annual_discount_percent' => 25,
            'features' => [
                'Full basic session setup',
                'Unlimited saved sessions',
                'Join ayahs together and memory-word highlights',
                'AI recitation',
                'AI memorisation checker',
                'Manual self-assessment recording + self recording',
                'Advanced analysis',
                'Download for offline listening',
                'Structured Custom Hifz Plan',
                'Spaced Session Retention',
                'Adaptive Revision Scheduling',
                'Progress Tracking',
            ],
        ],
    ],
];
